### PR TITLE
README.md: re-write example using lower-level API

### PR DESCRIPTION
**Pull request by LambdaP**
`hyper` will eventually depreciate
	`hyper::Server` and `hyper::service::make_service_fn`,
	in favor of lower-level API constructs
	like `hyper::server::conn::Http`.
This commit makes the example more idiomatic in that regard.

Note that `hyper`'s future API is not yet stabilized,
	and that `hyper::server::conn::Http` itself
	will be replaced by something else,
	but that change should be very lightweight in comparison, i.e.,

```rust
    let mut http = hyper::server::conn::Http::new();
    http.http1_only(true);
    http.http1_keep_alive(true);
```

will eventually have to initialize an object
	that follows the new API.

### CODE REVIEW

**Comment by de-vri-es** [comment]
Ah, very nice. Thanks for the PR!

Note that the `README.md` is generated from the module level docs in `lib.rs`. Could you update the example in `lib.rs`? You can then regenerate the README with `cargo-readme`, or I can do that bit (but I do want them to remain in sync).

**Comment by LambdaP** [comment]
Sure, I will do that.

**Comment by LambdaP** [comment]
It is done, and it also passes the tests from `cargo test`, which it didn't for stupid reasons (typo in imports, `info!` macro remaining in the code…).

As you might have noticed, there are unrelated updates in `README.md` because it wasn’t in sync with the last version of `lib.rs`.

**Comment by de-vri-es** [comment]
Thanks! Looks good :D

**Comment by de-vri-es** [comment]
Released as `v0.8.2` :rocket: Thanks again!

**Pull request merged**
