### PR TITLE
Bump tokio-tungstenite version to 0.15

### PR DESCRIPTION
**Pull request by ErwanDL**
Build and tests seem to be passing with no required change.

### CODE REVIEW

**Comment by de-vri-es** [comment]
Cool, thanks!

Note that "0.15" is not less restrictive than "0.15.0". Cargo automatically selects a semver compatible version, so they both allow any patch version.

**Comment by de-vri-es** [comment]
Released as 0.4.0 :)

Thanks again!

**Comment by ErwanDL** [comment]
Oh I didn't know that 0.15.0 and 0.15 were equivalent, thanks for the info ! And thanks for the release :)

**Comment by de-vri-es** [comment]
> Oh I didn't know that 0.15.0 and 0.15 were equivalent, thanks for the info ! And thanks for the release :)

Maybe there are some subtle differences in which pre-release versions are accepted, but I think they are really fully equivalent :)

I tend to specify the patch version too, because it ensures no older patch version is used, which I would not have tested with. It may have included an important bug fix.

More importantly, below version 1.0.0, the patch version often has the function of the minor version, which means that backwards compatible API changes (usually additions) are allowed. But then, if cargo chooses an older version it might break compilation, so you really need to specify a minimum 0.x.y. Of course, with `0.x.0` it doesn't matter, but I do like to be explicit :)

**Pull request merged**
